# Copyright (C) 2021 DreiMu
#
#This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version=1.0

[servers]
# Should be the domain you put in if you connect to the server and the value should be the name with pterodactyl
# "domain" = "velocity server name" (Optional)
"server1.example.com" = "server1"
"server2.example.com" = "server2"

[motds]
# [motds.(velocity server name)]
    [motds.server1]
    motd = "MOTD server 1"
    favicon = "server1"
    id = "ptero-id"
    [motds.server2]
    motd = "passthrough"
    favicon = "passthrough"
    id = "ptero-id"

[api]
endpoint = "https://ptero.example.com/api"
key = "API Key"

[messages]
redirect_timer = "You are getting redirected in 30 seconds. If it doesn't work, try again later"
offline_noperms = "This server is offline and you don't have the permissions to start him"
